# Generated by Django 2.2.3 on 2019-08-30 08:23

from django.db import migrations, models
import store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20190829_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=store_app.models.image_folder, verbose_name='Изображение'),
        ),
    ]
