# Generated by Django 2.2.3 on 2019-09-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_auto_20190831_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='store_app.Category', verbose_name='Категория'),
        ),
    ]
