# Generated by Django 2.2.3 on 2019-09-02 08:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_auto_20190902_1059'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store_app.Category', verbose_name='Категория'),
        ),
    ]
