# Generated by Django 2.2.3 on 2019-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, to='store_app.CartItem'),
        ),
    ]
