# Generated by Django 2.2.3 on 2019-09-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_auto_20190902_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
