# Generated by Django 2.2.4 on 2019-09-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_auto_20190903_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['id']},
        ),
    ]
